x-common: &common
  env_file:
    - .env.prod
  restart: unless-stopped

services:
  django-ptb:
    <<: [*common]
    container_name: django-ptb-website
    build:
      context: .
      dockerfile: Dockerfile
    image: django-ptb
    volumes:
      - staticfiles-data:/var/www/static
      - .:/website
    command: gunicorn -c config/gunicorn.py -k uvicorn.workers.UvicornWorker config.asgi:application

  django-ptb-proxy:
    <<: [*common]
    container_name: django-ptb-proxy
    image: nginx:alpine-slim
    volumes:
      - type: volume
        source: staticfiles-data
        target: /usr/share/nginx/html/static
        read_only: true
        volume:
          nocopy: true
      - type: bind
        source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - django-ptb
    # ports:
    #   - 8000:80

  django-ptb-bot:
    <<: [*common]
    container_name: django-ptb-bot
    image: django-ptb
    volumes:
      - .:/website
    depends_on:
      - django-ptb
    command: python manage.py runbot

volumes:
  staticfiles-data:
